### PR TITLE
Added ability to delete records on cascade

### PR DESCRIPTION
**Pull request by brandonferens**
This PR solves two features I was needing.

The first is that I needed the ability to delete an activity record if its subject/parent model was deleted. I didn't want the activity feed display items that were orphaned. A static property has been added and some other methods put in place to allow this functionality.

The second need allows both the `getRecords()` and `getUserActivity()` methods to return activity matching certain event types. For a forum user's profile, things like logging in or logging out are irrelevant. So a second and third method parameter, respectively, have been added to allow the option of passing in either a string such as `created_post` or an array `['created_post', 'updated_post']`.

I attempted to write tests to cover the new functionality and am still willing to do that. However, some changes have been made to `orchestra/testbench` and the test suite needs to be fixed to match these breaking changes. If you get that updated, let me know and I can write tests.

### CODE REVIEW

**Comment by Hyleeh** [comment]
Awesome, I'll check the test suite at my earliest convenience

Thanks for the PR

**Comment by brandonferens** [comment]
Thanks. I have a few more additions and refactors I'd like to do. I'll send them your way when they are ready.

**Comment by Hyleeh** [comment]
Sure thing, will try to fix testbench in the meanwhile👍🏻

**Comment by Hyleeh** [comment]
Updated composer.json to choose the correct testbench suite. Unfortunately it is the laravel 5.2, as this package was initially developed for that. Should work now

**Comment by brandonferens** [comment]
Excellent. Thanks @Hyleeh

**Pull request merged**
